# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false

language: generic

branches:
  only:
    - master

env:
  - PYVER="3.7"
  - PYVER="3.6"
  - PYVER="3.5"
  - PYVER="2.7"

install:
  # Install Miniconda.
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh > miniconda.sh
  - openssl md5 miniconda.sh | grep e1045ee415162f944b6aebfe560b8fee
  - bash miniconda.sh -b -p ~/miniconda
  - rm miniconda.sh
  - source ~/miniconda/etc/profile.d/conda.sh
  - conda activate
  - conda config --set show_channel_urls true
  - conda update -y -n root --all
  - conda install -y -n root conda-build
  - conda clean -tipsy

  # Create the test environment.
  - conda create -y -n testenv python="${PYVER}"
  - conda env update -n testenv --file environment_ci.yml
  - conda activate testenv

# command to run tests, e.g. python setup.py test
script:
  - coverage erase
  - coverage run --append --source . setup.py --version
  - coverage run --append --source . setup.py build_ext --inplace
  - coverage run --append --source . setup.py test
  - coverage report -m

# Report coverage
after_success:
  - conda activate
  - conda create -y -n dplenv python="3.5";
  - conda remove -y --force -n dplenv openssl
  - conda env update -n dplenv --file environment_dpl.yml
  - conda list --full-name -n dplenv openssl || conda install -y -n dplenv openssl
  - conda activate dplenv
  - coveralls

# Disable email notifications.
notifications:
  email: false


